baseURL = "http://example.org/"
languageCode = "en-us"
title = "Livnat's New Site"
theme = "codex"
publishDir = "../dist"



[params]
  twitter = "your-twitter-handle"
  github = "your-github-handle"
  iconTitles = ["Twitter", "GitHub"]

[[menu.main]]
      identifier = "about"
      name = "about"
      title = "About"
      url = "/"

[[menu.main]]
      identifier = "blog"
      name = "blog"
      title = "Blog"
      url = "/blog"

[[menu.main]]
      identifier = "photography"
      name = "photography"
      title = "Photography"
      url = "/photography"