baseURL = "https://lennyda.github.io/myBlog/"
canonifyURLs = "true"
languageCode = "en-us"
title = "Livnat's New Site"
theme = "codex"
copyright = "© {year} LennyDa (Livnat David)"

[params]
  github = "https://github.com/<your handle>"
  # email = "mailto:<your email>"
  facebook = "https://facebook.com/<your handle>"
  # gitlab = "https://gitlab.com/<your handle>"
  instagram = "https://instagram.com/<your handle>"
  # linkedin = "<link to your profile>"
  youtube = "https://www.youtube.com/channel/<your channel>"
  iconTitles = ["GitHub", "Facebook", "Instagram", "Youtube"]

[[menu.main]]
      identifier = "hompage"
      name = "Hompage"
      title = "Hompage"
      url = "/"
      Weight = -100

[[menu.main]]
      identifier = "about"
      name = "About"
      title = "About"
      url = "/about-page"

[[menu.main]]
      identifier = "blog"
      name = "Blog"
      title = "Blog"
      url = "/blog"